import re
from peft import LoraConfig, get_peft_model, PeftModel
import torch
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
)

def cypher2path(cypher_query: str) -> list[tuple[str, str, str, str]]:
    path = re.findall(r"(?:\(|-\[)(x|r)(\d):([^ \)\]]+)(?: \{name: \"(.+)\"\})?(?:\)|\]-)", cypher_query)
    return path

def block2cypher(x_r: str, num: str, label_or_type: str, name: str) -> str:
    if x_r == 'x':
        prop_string = f" {{name: \"{name}\"}}" if name != '' else ""
        return f"(x{num}:{label_or_type}{prop_string})"
    elif x_r == 'r':
        return f"-[r{num}:{label_or_type}]-"

def path2cypher(path: list[tuple[str, str, str, str]]) -> str:
    query = "MATCH "
    for x_r, num, labelOrType, name in path:
        if x_r == 'x' or x_r == 'r':
            query += block2cypher(x_r, num, labelOrType, name)
        elif x_r == '':
            query += f" RETURN x{num}.name as name"
    return query

def get_options(current_path: list[tuple[str, str, str, str]], all_paths: list[list[tuple[str, str, str, str]]]) -> list[str]:
    options = set()
    for path in all_paths:
        for i, (x_r, num, labelOrType, name) in enumerate(path):
            if i==len(current_path):
                options.add(block2cypher(x_r, num, labelOrType, name))
                break
            if x_r != current_path[i][0] or str(num) != current_path[i][1] or labelOrType != current_path[i][2] or name != current_path[i][3]:
                break #path does not match
    return options

def load_model():
    # Model
    model_name = "neo4j/text2cypher-gemma-2-9b-it-finetuned-2024v1"
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_use_double_quant=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
    )
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=bnb_config,
        torch_dtype=torch.bfloat16,
        attn_implementation="eager",
        low_cpu_mem_usage=True,
    )

    #lora_config = LoraConfig( r=64, lora_alpha=64, target_modules=None, lora_dropout=0.05, bias="none", task_type="CAUSAL_LM", )
    peft_model = PeftModel.from_pretrained(model, './checkpoint-615', torch_dtype=torch.bfloat16, is_trainable=False)
    return peft_model, tokenizer


def format_tokenize_and_score_prompt_and_cypher(model, tokenizer, data, cypher):
    schema = 'Relationships without direction (:Disease)-[:OFF_LABEL_USE]-(:Drug), (:Drug)-[:OFF_LABEL_USE]-(:Disease), (:Disease)-[:ASSOCIATED_WITH]-(:GeneOrProtein), (:GeneOrProtein)-[:ASSOCIATED_WITH]-(:Disease), (:Disease)-[:PARENT_CHILD]-(:Disease), (:Disease)-[:PHENOTYPE_ABSENT]-(:EffectOrPhenotype), (:EffectOrPhenotype)-[:PHENOTYPE_ABSENT]-(:Disease), (:Disease)-[:PHENOTYPE_PRESENT]-(:EffectOrPhenotype), (:EffectOrPhenotype)-[:PHENOTYPE_PRESENT]-(:Disease), (:Disease)-[:LINKED_TO]-(:Exposure), (:Exposure)-[:LINKED_TO]-(:Disease), (:Disease)-[:CONTRAINDICATION]-(:Drug), (:Drug)-[:CONTRAINDICATION]-(:Disease), (:Disease)-[:INDICATION]-(:Drug), (:Drug)-[:INDICATION]-(:Disease), (:GeneOrProtein)-[:PPI]-(:GeneOrProtein), (:GeneOrProtein)-[:INTERACTS_WITH]-(:MolecularFunction), (:MolecularFunction)-[:INTERACTS_WITH]-(:GeneOrProtein), (:GeneOrProtein)-[:INTERACTS_WITH]-(:BiologicalProcess), (:BiologicalProcess)-[:INTERACTS_WITH]-(:GeneOrProtein), (:GeneOrProtein)-[:INTERACTS_WITH]-(:CellularComponent), (:CellularComponent)-[:INTERACTS_WITH]-(:GeneOrProtein), (:GeneOrProtein)-[:EXPRESSION_PRESENT]-(:Anatomy), (:Anatomy)-[:EXPRESSION_PRESENT]-(:GeneOrProtein), (:GeneOrProtein)-[:EXPRESSION_ABSENT]-(:Anatomy), (:Anatomy)-[:EXPRESSION_ABSENT]-(:GeneOrProtein), (:GeneOrProtein)-[:INTERACTS_WITH]-(:Pathway), (:Pathway)-[:INTERACTS_WITH]-(:GeneOrProtein), (:GeneOrProtein)-[:TARGET]-(:Drug), (:Drug)-[:TARGET]-(:GeneOrProtein), (:GeneOrProtein)-[:TRANSPORTER]-(:Drug), (:Drug)-[:TRANSPORTER]-(:GeneOrProtein), (:GeneOrProtein)-[:CARRIER]-(:Drug), (:Drug)-[:CARRIER]-(:GeneOrProtein), (:GeneOrProtein)-[:ENZYME]-(:Drug), (:Drug)-[:ENZYME]-(:GeneOrProtein), (:GeneOrProtein)-[:ASSOCIATED_WITH]-(:EffectOrPhenotype), (:EffectOrPhenotype)-[:ASSOCIATED_WITH]-(:GeneOrProtein), (:GeneOrProtein)-[:INTERACTS_WITH]-(:Exposure), (:Exposure)-[:INTERACTS_WITH]-(:GeneOrProtein), (:MolecularFunction)-[:PARENT_CHILD]-(:MolecularFunction), (:MolecularFunction)-[:INTERACTS_WITH]-(:Exposure), (:Exposure)-[:INTERACTS_WITH]-(:MolecularFunction), (:Drug)-[:SYNERGISTIC_INTERACTION]-(:Drug), (:Drug)-[:SIDE_EFFECT]-(:EffectOrPhenotype), (:EffectOrPhenotype)-[:SIDE_EFFECT]-(:Drug), (:Pathway)-[:PARENT_CHILD]-(:Pathway), (:Anatomy)-[:PARENT_CHILD]-(:Anatomy), (:EffectOrPhenotype)-[:PARENT_CHILD]-(:EffectOrPhenotype), (:BiologicalProcess)-[:PARENT_CHILD]-(:BiologicalProcess), (:BiologicalProcess)-[:INTERACTS_WITH]-(:Exposure), (:Exposure)-[:INTERACTS_WITH]-(:BiologicalProcess), (:CellularComponent)-[:PARENT_CHILD]-(:CellularComponent), (:CellularComponent)-[:INTERACTS_WITH]-(:Exposure), (:Exposure)-[:INTERACTS_WITH]-(:CellularComponent), (:Exposure)-[:PARENT_CHILD]-(:Exposure)'

    instruction = (
        "Generate Cypher statement to query a graph database. "
        "Use only the provided relationship types and properties in the schema. \n"
        "Schema: {schema} \n Question: {question}  \n Cypher output: "
    )
    label = "{cypher}"

    chat = [
        {"role": "user", "content": instruction.format(schema=schema, question=data['question'])},
        {"role": "model", "content": label.format(cypher=cypher)},
    ]
    input_ids = tokenizer.apply_chat_template(chat, tokenize=True, return_tensors='pt')
    output = model(input_ids, labels=input_ids)
    loss = output.loss.cpu().detach().numpy()
    return -loss.item()

beam_width = 1

model, tokenizer = load_model()

dataset = torch.load('prime-data/dataset.pt', weights_only=False)

i = 0
all_paths = [
    [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'ASSOCIATED_WITH', ''),
  ('x', '2', 'Disease', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'MolecularFunction', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'Pathway', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'BiologicalProcess', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'CellularComponent', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'EXPRESSION_PRESENT', ''),
  ('x', '2', 'Anatomy', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'EXPRESSION_ABSENT', ''),
  ('x', '2', 'Anatomy', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'INDICATION', ''),
  ('x', '2', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'OFF_LABEL_USE', ''),
  ('x', '2', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SIDE_EFFECT', ''),
  ('x', '2', 'EffectOrPhenotype', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'MolecularFunction', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'Pathway', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'BiologicalProcess', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'CellularComponent', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'EXPRESSION_PRESENT', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'PPI', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'EXPRESSION_ABSENT', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'TARGET', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'TRANSPORTER', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'CARRIER', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'ASSOCIATED_WITH', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'CONTRAINDICATION', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'ASSOCIATED_WITH', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'ASSOCIATED_WITH', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'LINKED_TO', ''),
  ('x', '3', 'Exposure', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'ASSOCIATED_WITH', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'ASSOCIATED_WITH', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'CONTRAINDICATION', ''),
  ('x', '3', 'Drug', 'Lidocaine')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'MolecularFunction', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'MolecularFunction', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'MolecularFunction', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'Pathway', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'Pathway', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'Pathway', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'BiologicalProcess', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'BiologicalProcess', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'BiologicalProcess', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'CellularComponent', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'CellularComponent', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'CellularComponent', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'EXPRESSION_PRESENT', ''),
  ('x', '2', 'Anatomy', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'EXPRESSION_PRESENT', ''),
  ('x', '2', 'Anatomy', ''),
  ('r', '2', 'EXPRESSION_PRESENT', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'EXPRESSION_PRESENT', ''),
  ('x', '2', 'Anatomy', ''),
  ('r', '2', 'EXPRESSION_ABSENT', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'EXPRESSION_ABSENT', ''),
  ('x', '2', 'Anatomy', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'EXPRESSION_ABSENT', ''),
  ('x', '2', 'Anatomy', ''),
  ('r', '2', 'EXPRESSION_PRESENT', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'EXPRESSION_ABSENT', ''),
  ('x', '2', 'Anatomy', ''),
  ('r', '2', 'EXPRESSION_ABSENT', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'PPI', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'TARGET', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'MolecularFunction', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'Pathway', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'BiologicalProcess', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'CellularComponent', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'EXPRESSION_PRESENT', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'EXPRESSION_ABSENT', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ENZYME', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'TARGET', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'PPI', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'MolecularFunction', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'Pathway', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'BiologicalProcess', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'CellularComponent', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'EXPRESSION_PRESENT', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'CARRIER', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'EXPRESSION_ABSENT', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'TRANSPORTER', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'PPI', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'TARGET', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'TRANSPORTER', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'MolecularFunction', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'Pathway', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'BiologicalProcess', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'CellularComponent', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'EXPRESSION_PRESENT', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'CARRIER', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ENZYME', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'EXPRESSION_ABSENT', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'CONTRAINDICATION', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'INDICATION', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'PHENOTYPE_ABSENT', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'PHENOTYPE_PRESENT', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'LINKED_TO', ''),
  ('x', '3', 'Exposure', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'OFF_LABEL_USE', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'GeneOrProtein', 'SLC13A4')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'INDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'INDICATION', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'INDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'INDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'CONTRAINDICATION', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'INDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'OFF_LABEL_USE', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'INDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'INDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'PHENOTYPE_PRESENT', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'OFF_LABEL_USE', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'CONTRAINDICATION', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'OFF_LABEL_USE', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'INDICATION', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'OFF_LABEL_USE', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'OFF_LABEL_USE', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'OFF_LABEL_USE', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'OFF_LABEL_USE', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SIDE_EFFECT', ''),
  ('x', '2', 'EffectOrPhenotype', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SIDE_EFFECT', ''),
  ('x', '2', 'EffectOrPhenotype', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SIDE_EFFECT', ''),
  ('x', '2', 'EffectOrPhenotype', ''),
  ('r', '2', 'PHENOTYPE_PRESENT', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SIDE_EFFECT', ''),
  ('x', '2', 'EffectOrPhenotype', ''),
  ('r', '2', 'SIDE_EFFECT', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SIDE_EFFECT', ''),
  ('x', '2', 'EffectOrPhenotype', ''),
  ('r', '2', 'PHENOTYPE_ABSENT', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'CARRIER', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'ENZYME', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'TARGET', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'TRANSPORTER', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'CONTRAINDICATION', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'INDICATION', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'SIDE_EFFECT', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'OFF_LABEL_USE', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'MolecularFunction', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'Pathway', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'BiologicalProcess', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'CellularComponent', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'EXPRESSION_PRESENT', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'PPI', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'EXPRESSION_ABSENT', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'TARGET', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'TRANSPORTER', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'CARRIER', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'PPI', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'ASSOCIATED_WITH', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'CONTRAINDICATION', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'ASSOCIATED_WITH', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'ASSOCIATED_WITH', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'LINKED_TO', ''),
  ('x', '3', 'Exposure', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'ASSOCIATED_WITH', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'MolecularFunction', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'MolecularFunction', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'MolecularFunction', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'Pathway', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'Pathway', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'Pathway', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'BiologicalProcess', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'BiologicalProcess', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'BiologicalProcess', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'CellularComponent', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'CellularComponent', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'INTERACTS_WITH', ''),
  ('x', '2', 'CellularComponent', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'EXPRESSION_PRESENT', ''),
  ('x', '2', 'Anatomy', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'EXPRESSION_PRESENT', ''),
  ('x', '2', 'Anatomy', ''),
  ('r', '2', 'EXPRESSION_PRESENT', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'EXPRESSION_PRESENT', ''),
  ('x', '2', 'Anatomy', ''),
  ('r', '2', 'EXPRESSION_ABSENT', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'EXPRESSION_ABSENT', ''),
  ('x', '2', 'Anatomy', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'EXPRESSION_ABSENT', ''),
  ('x', '2', 'Anatomy', ''),
  ('r', '2', 'EXPRESSION_PRESENT', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'GeneOrProtein', 'SLC13A4'),
  ('r', '1', 'EXPRESSION_ABSENT', ''),
  ('x', '2', 'Anatomy', ''),
  ('r', '2', 'EXPRESSION_ABSENT', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'PPI', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'TARGET', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'MolecularFunction', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'Pathway', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'BiologicalProcess', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'CellularComponent', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'EXPRESSION_PRESENT', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'EXPRESSION_ABSENT', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ENZYME', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'ENZYME', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'TARGET', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'PPI', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'MolecularFunction', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'Pathway', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'BiologicalProcess', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'CellularComponent', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'EXPRESSION_PRESENT', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'CARRIER', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'EXPRESSION_ABSENT', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TARGET', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'TRANSPORTER', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'PPI', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'TARGET', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'TRANSPORTER', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'MolecularFunction', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'Pathway', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'BiologicalProcess', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'INTERACTS_WITH', ''),
  ('x', '3', 'CellularComponent', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'EXPRESSION_PRESENT', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'CARRIER', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'ENZYME', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'TRANSPORTER', ''),
  ('x', '2', 'GeneOrProtein', ''),
  ('r', '2', 'EXPRESSION_ABSENT', ''),
  ('x', '3', 'Anatomy', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'CONTRAINDICATION', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'INDICATION', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'PHENOTYPE_ABSENT', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'PHENOTYPE_PRESENT', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'LINKED_TO', ''),
  ('x', '3', 'Exposure', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'CONTRAINDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'OFF_LABEL_USE', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'INDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'INDICATION', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'INDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'INDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'CONTRAINDICATION', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'INDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'OFF_LABEL_USE', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'INDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'INDICATION', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'PHENOTYPE_PRESENT', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'OFF_LABEL_USE', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'CONTRAINDICATION', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'OFF_LABEL_USE', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'INDICATION', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'OFF_LABEL_USE', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'OFF_LABEL_USE', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'OFF_LABEL_USE', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'OFF_LABEL_USE', ''),
  ('x', '2', 'Disease', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SIDE_EFFECT', ''),
  ('x', '2', 'EffectOrPhenotype', ''),
  ('r', '2', 'ASSOCIATED_WITH', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SIDE_EFFECT', ''),
  ('x', '2', 'EffectOrPhenotype', ''),
  ('r', '2', 'PARENT_CHILD', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SIDE_EFFECT', ''),
  ('x', '2', 'EffectOrPhenotype', ''),
  ('r', '2', 'PHENOTYPE_PRESENT', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SIDE_EFFECT', ''),
  ('x', '2', 'EffectOrPhenotype', ''),
  ('r', '2', 'SIDE_EFFECT', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SIDE_EFFECT', ''),
  ('x', '2', 'EffectOrPhenotype', ''),
  ('r', '2', 'PHENOTYPE_ABSENT', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'CARRIER', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'ENZYME', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'TARGET', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'TRANSPORTER', ''),
  ('x', '3', 'GeneOrProtein', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'CONTRAINDICATION', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'INDICATION', ''),
  ('x', '3', 'Disease', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'SIDE_EFFECT', ''),
  ('x', '3', 'EffectOrPhenotype', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '3', 'Drug', '')],
 [('x', '1', 'Drug', 'Lidocaine'),
  ('r', '1', 'SYNERGISTIC_INTERACTION', ''),
  ('x', '2', 'Drug', ''),
  ('r', '2', 'OFF_LABEL_USE', ''),
  ('x', '3', 'Disease', '')]]

data = dataset['test'][i]


queries1 = [f"MATCH {part}" for part in get_options([], all_paths)]
for query in queries1:
    print(query)

optionss = [get_options(cypher2path(query), all_paths) for query in queries1]
queries2 = [query + option for query, options in zip(queries1, optionss) for option in options]

# top_queries2, probs = zip(*sorted([(query, score(f"{prompt}{query}")) for query in queries2], key=lambda x: x[1], reverse=True)[:beam_width])
top_queries2, probs = zip(*sorted([(query, format_tokenize_and_score_prompt_and_cypher(model, tokenizer, data, query))
                                   for query in queries2],
                                  key=lambda x: x[1], reverse=True)[:beam_width]
                          )
    #*sorted([(query, score(prompt, query)) for query in queries2], key=lambda x: x[1], reverse=True)[:beam_width])
for query, prob in zip(top_queries2, probs):
    print(query, prob)

optionss = [get_options(cypher2path(query), all_paths) for query in top_queries2]
queries3 = [query + option for query, options in zip(top_queries2, optionss) for option in options]

# top_queries3, probs = zip(*sorted([(query, score(f"{prompt}{query}")) for query in queries3], key=lambda x: x[1], reverse=True)[:beam_width])
#top_queries3, probs = zip(
#    *sorted([(query, score(prompt, query)) for query in queries3], key=lambda x: x[1], reverse=True)[:beam_width])
top_queries3, probs = zip(*sorted([(query, format_tokenize_and_score_prompt_and_cypher(model, tokenizer, data, query))
                                   for query in queries3],
                                  key=lambda x: x[1], reverse=True)[:beam_width]
                          )
for query, prob in zip(top_queries3, probs):
    print(query, prob)

optionss = [get_options(cypher2path(query), all_paths) for query in top_queries3]
# queries4 = [query + option for query, options in zip(top_queries3, optionss) for option in options]
queries4 = [query + option for query, options in zip(top_queries3, optionss) for option in options if
            option is not None]

# top_queries4, probs = zip(*sorted([(query, score(f"{prompt}{query}")) for query in queries4], key=lambda x: x[1], reverse=True)[:beam_width])
#top_queries4, probs = zip(
#    *sorted([(query, score(prompt, query)) for query in queries4], key=lambda x: x[1], reverse=True)[:beam_width])
top_queries4, probs = zip(*sorted([(query, format_tokenize_and_score_prompt_and_cypher(model, tokenizer, data, query))
                                   for query in queries4],
                                  key=lambda x: x[1], reverse=True)[:beam_width]
                          )
for query, prob in zip(top_queries4, probs):
    print(query, prob)

optionss = [get_options(cypher2path(query), all_paths) for query in top_queries4]
queries5 = [query + option for query, options in zip(top_queries4, optionss) for option in options]

# top_queries5, probs = zip(*sorted([(query, score(f"{prompt}{query}")) for query in queries5], key=lambda x: x[1], reverse=True)[:beam_width])
#top_queries5, probs = zip(
#    *sorted([(query, score(prompt, query)) for query in queries5], key=lambda x: x[1], reverse=True)[:beam_width])
top_queries5, probs = zip(*sorted([(query, format_tokenize_and_score_prompt_and_cypher(model, tokenizer, data, query))
                                   for query in queries5],
                                  key=lambda x: x[1], reverse=True)[:beam_width]
                          )
for query, prob in zip(top_queries5, probs):
    print(query, prob)